<?php

namespace NewsletterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmailSubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailSubscriberRepository extends EntityRepository
{
}
