<?php

namespace NewsletterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubscriberGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberGroupRepository extends EntityRepository
{
}
